# Generated by Django 2.2.7 on 2019-11-20 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memo',
            options={'ordering': ['-id']},
        ),
    ]
